services:
  - postgresql
  - memcached
addons:
  postgresql: '9.5'
  apt:
    packages:
      - postgresql-server-dev-9.5
language: ruby
rvm:
  - 2.3.0
before_install: gem install bundler -v 1.17.3
script: rake test
